// Full-guide data for ALL countries.
// LANGS: per-language survival phrases (local text + TTS code)
// LANG_BY_COUNTRY: country a2 → language key
// EXTRA: per-country cities/sights/foods as [English, 中文] pairs
// SUBNOTES: safety/taboo general notes per UN subregion (zh + en)

const PHRASE_EN = [
  ["Hello", "/həˈloʊ/", "你好"],
  ["Thank you", "/ˈθæŋk juː/", "谢谢"],
  ["How much is it?", "/haʊ ˈmʌtʃ ɪz ɪt/", "多少钱？"],
  ["Where is the toilet?", "/wɛr ɪz ðə ˈtɔɪlət/", "洗手间在哪？"],
  ["Delicious!", "/dɪˈlɪʃəs/", "好吃！"]
];

const LANGS = {
  en: { tts: "en-US", zh: "英语", en: "English", p: ["Hello", "Thank you", "How much is it?", "Where is the toilet?", "Delicious!"] },
  es: { tts: "es-ES", zh: "西班牙语", en: "Spanish", p: ["Hola", "Gracias", "¿Cuánto cuesta?", "¿Dónde está el baño?", "¡Delicioso!"] },
  fr: { tts: "fr-FR", zh: "法语", en: "French", p: ["Bonjour", "Merci", "C'est combien ?", "Où sont les toilettes ?", "Délicieux !"] },
  pt: { tts: "pt-PT", zh: "葡萄牙语", en: "Portuguese", p: ["Olá", "Obrigado", "Quanto custa?", "Onde é a casa de banho?", "Delicioso!"] },
  ar: { tts: "ar-SA", zh: "阿拉伯语", en: "Arabic", p: ["مرحبا", "شكراً", "بكم هذا؟", "أين الحمام؟", "لذيذ!"] },
  ru: { tts: "ru-RU", zh: "俄语", en: "Russian", p: ["Здравствуйте", "Спасибо", "Сколько стоит?", "Где туалет?", "Очень вкусно!"] },
  de: { tts: "de-DE", zh: "德语", en: "German", p: ["Hallo", "Danke", "Wie viel kostet das?", "Wo ist die Toilette?", "Lecker!"] },
  it: { tts: "it-IT", zh: "意大利语", en: "Italian", p: ["Ciao", "Grazie", "Quanto costa?", "Dov'è il bagno?", "Buonissimo!"] },
  nl: { tts: "nl-NL", zh: "荷兰语", en: "Dutch", p: ["Hallo", "Dank je", "Hoeveel kost het?", "Waar is het toilet?", "Lekker!"] },
  el: { tts: "el-GR", zh: "希腊语", en: "Greek", p: ["Γεια σας", "Ευχαριστώ", "Πόσο κάνει;", "Πού είναι η τουαλέτα;", "Πολύ νόστιμο!"] },
  tr: { tts: "tr-TR", zh: "土耳其语", en: "Turkish", p: ["Merhaba", "Teşekkürler", "Ne kadar?", "Tuvalet nerede?", "Çok lezzetli!"] },
  zh: { tts: "zh-CN", zh: "中文", en: "Chinese", p: ["你好", "谢谢", "多少钱？", "洗手间在哪里？", "好吃！"] },
  ja: { tts: "ja-JP", zh: "日语", en: "Japanese", p: ["こんにちは", "ありがとうございます", "いくらですか", "トイレはどこですか", "おいしい！"] },
  ko: { tts: "ko-KR", zh: "韩语", en: "Korean", p: ["안녕하세요", "감사합니다", "얼마예요?", "화장실이 어디예요?", "맛있어요!"] },
  vi: { tts: "vi-VN", zh: "越南语", en: "Vietnamese", p: ["Xin chào", "Cảm ơn", "Bao nhiêu tiền?", "Nhà vệ sinh ở đâu?", "Ngon quá!"] },
  th: { tts: "th-TH", zh: "泰语", en: "Thai", p: ["สวัสดี", "ขอบคุณ", "เท่าไหร่", "ห้องน้ำอยู่ที่ไหน", "อร่อย!"] },
  id: { tts: "id-ID", zh: "印尼语", en: "Indonesian", p: ["Halo", "Terima kasih", "Berapa harganya?", "Di mana toilet?", "Enak!"] },
  ms: { tts: "ms-MY", zh: "马来语", en: "Malay", p: ["Halo", "Terima kasih", "Berapa harga?", "Tandas di mana?", "Sedap!"] },
  tl: { tts: "fil-PH", zh: "菲律宾语", en: "Filipino", p: ["Kumusta", "Salamat", "Magkano ito?", "Nasaan ang banyo?", "Masarap!"] },
  my: { tts: "my-MM", zh: "缅甸语", en: "Burmese", p: ["မင်္ဂလာပါ", "ကျေးဇူးတင်ပါတယ်", "ဘယ်လောက်လဲ", "အိမ်သာဘယ်မှာလဲ", "အရသာရှိတယ်!"] },
  lo: { tts: "lo-LA", zh: "老挝语", en: "Lao", p: ["ສະບາຍດີ", "ຂອບໃຈ", "ເທົ່າໃດ?", "ຫ້ອງນ້ຳຢູ່ໃສ?", "ແຊບຫຼາຍ!"] },
  km: { tts: "km-KH", zh: "高棉语", en: "Khmer", p: ["ជំរាបសួរ", "អរគុណ", "តម្លៃប៉ុន្មាន?", "បង្គន់នៅឯណា?", "ឆ្ងាញ់ណាស់!"] },
  hi: { tts: "hi-IN", zh: "印地语", en: "Hindi", p: ["नमस्ते", "धन्यवाद", "कितने का है?", "शौचालय कहाँ है?", "बहुत स्वादिष्ट!"] },
  ur: { tts: "ur-PK", zh: "乌尔都语", en: "Urdu", p: ["السلام علیکم", "شکریہ", "یہ کتنے کا ہے؟", "بیت الخلا کہاں ہے؟", "بہت مزیدار!"] },
  bn: { tts: "bn-BD", zh: "孟加拉语", en: "Bengali", p: ["নমস্কার", "ধন্যবাদ", "এটার দাম কত?", "টয়লেট কোথায়?", "খুব সুস্বাদু!"] },
  ne: { tts: "ne-NP", zh: "尼泊尔语", en: "Nepali", p: ["नमस्ते", "धन्यवाद", "यसको कति हो?", "शौचालय कहाँ छ?", "मीठो छ!"] },
  si: { tts: "si-LK", zh: "僧伽罗语", en: "Sinhala", p: ["ආයුබෝවන්", "ස්තූතියි", "මේක කීයද?", "වැසිකිළිය කොහෙද?", "රසයි!"] },
  dv: { tts: "dv-MV", zh: "迪维希语", en: "Dhivehi", p: ["Assalaamu alaikum", "Shukuriyyaa", "Mee kihaavareh?", "Faakhaanaa kobaitha?", "Varah meeru!"] },
  dz: { tts: "dz-BT", zh: "宗卡语", en: "Dzongkha", p: ["Kuzu zangpo la", "Kadrin chhe la", "Gadem chi mo?", "Chhabsa gati mo?", "Zhim be du!"] },
  fa: { tts: "fa-IR", zh: "波斯语", en: "Persian", p: ["سلام", "ممنون", "چند است؟", "دستشویی کجاست؟", "خوشمزه است!"] },
  he: { tts: "he-IL", zh: "希伯来语", en: "Hebrew", p: ["שלום", "תודה", "כמה זה עולה?", "איפה השירותים?", "טעים מאוד!"] },
  mn: { tts: "mn-MN", zh: "蒙古语", en: "Mongolian", p: ["Сайн байна уу", "Баярлалаа", "Энэ ямар үнэтэй вэ?", "Бие засах газар хаана байна?", "Маш амттай!"] },
  kk: { tts: "kk-KZ", zh: "哈萨克语", en: "Kazakh", p: ["Сәлеметсіз бе", "Рахмет", "Бұл қанша тұрады?", "Дәретхана қайда?", "Өте дәмді!"] },
  ky: { tts: "ky-KG", zh: "吉尔吉斯语", en: "Kyrgyz", p: ["Саламатсызбы", "Рахмат", "Канча турат?", "Даараткана кайда?", "Абдан даамдуу!"] },
  uz: { tts: "uz-UZ", zh: "乌兹别克语", en: "Uzbek", p: ["Assalomu alaykum", "Rahmat", "Bu qancha turadi?", "Hojatxona qayerda?", "Juda mazali!"] },
  tg: { tts: "tg-TJ", zh: "塔吉克语", en: "Tajik", p: ["Салом", "Ташаккур", "Ин чанд аст?", "Ҳоҷатхона куҷост?", "Хеле болаззат!"] },
  tk: { tts: "tk-TM", zh: "土库曼语", en: "Turkmen", p: ["Salam", "Sag boluň", "Näçe?", "Hajathana nirede?", "Örän tagamly!"] },
  az: { tts: "az-AZ", zh: "阿塞拜疆语", en: "Azerbaijani", p: ["Salam", "Təşəkkür edirəm", "Bu neçəyədir?", "Tualet haradadır?", "Çox dadlıdır!"] },
  ka: { tts: "ka-GE", zh: "格鲁吉亚语", en: "Georgian", p: ["გამარჯობა", "მადლობა", "რა ღირს?", "სად არის ტუალეტი?", "ძალიან გემრიელია!"] },
  hy: { tts: "hy-AM", zh: "亚美尼亚语", en: "Armenian", p: ["Բարև ձեզ", "Շնորհակալություն", "Ի՞նչ արժե", "Որտե՞ղ է զուգարանը", "Շատ համեղ է!"] },
  sw: { tts: "sw-KE", zh: "斯瓦希里语", en: "Swahili", p: ["Jambo", "Asante", "Bei gani?", "Choo kiko wapi?", "Tamu sana!"] },
  am: { tts: "am-ET", zh: "阿姆哈拉语", en: "Amharic", p: ["ሰላም", "አመሰግናለሁ", "ስንት ነው?", "መጸዳጃ ቤት የት ነው?", "ጣፋጭ ነው!"] },
  so: { tts: "so-SO", zh: "索马里语", en: "Somali", p: ["Salaan", "Mahadsanid", "Waa immisa?", "Musqusha aaway?", "Aad bay u macaan tahay!"] },
  pl: { tts: "pl-PL", zh: "波兰语", en: "Polish", p: ["Dzień dobry", "Dziękuję", "Ile to kosztuje?", "Gdzie jest toaleta?", "Pyszne!"] },
  cs: { tts: "cs-CZ", zh: "捷克语", en: "Czech", p: ["Dobrý den", "Děkuji", "Kolik to stojí?", "Kde je toaleta?", "Výborné!"] },
  sk: { tts: "sk-SK", zh: "斯洛伐克语", en: "Slovak", p: ["Dobrý deň", "Ďakujem", "Koľko to stojí?", "Kde je toaleta?", "Výborné!"] },
  hu: { tts: "hu-HU", zh: "匈牙利语", en: "Hungarian", p: ["Jó napot", "Köszönöm", "Mennyibe kerül?", "Hol a mosdó?", "Nagyon finom!"] },
  ro: { tts: "ro-RO", zh: "罗马尼亚语", en: "Romanian", p: ["Bună ziua", "Mulțumesc", "Cât costă?", "Unde este toaleta?", "Delicios!"] },
  bg: { tts: "bg-BG", zh: "保加利亚语", en: "Bulgarian", p: ["Здравейте", "Благодаря", "Колко струва?", "Къде е тоалетната?", "Много вкусно!"] },
  sr: { tts: "sr-RS", zh: "塞尔维亚语", en: "Serbian", p: ["Здраво", "Хвала", "Колико кошта?", "Где је тоалет?", "Веома укусно!"] },
  hr: { tts: "hr-HR", zh: "克罗地亚语", en: "Croatian", p: ["Dobar dan", "Hvala", "Koliko košta?", "Gdje je WC?", "Jako ukusno!"] },
  bs: { tts: "bs-BA", zh: "波斯尼亚语", en: "Bosnian", p: ["Dobar dan", "Hvala", "Koliko košta?", "Gdje je toalet?", "Vrlo ukusno!"] },
  sl: { tts: "sl-SI", zh: "斯洛文尼亚语", en: "Slovenian", p: ["Dober dan", "Hvala", "Koliko stane?", "Kje je stranišče?", "Zelo okusno!"] },
  mk: { tts: "mk-MK", zh: "马其顿语", en: "Macedonian", p: ["Здраво", "Благодарам", "Колку чини?", "Каде е тоалетот?", "Многу вкусно!"] },
  sq: { tts: "sq-AL", zh: "阿尔巴尼亚语", en: "Albanian", p: ["Përshëndetje", "Faleminderit", "Sa kushton?", "Ku është tualeti?", "Shumë e shijshme!"] },
  uk: { tts: "uk-UA", zh: "乌克兰语", en: "Ukrainian", p: ["Добрий день", "Дякую", "Скільки коштує?", "Де туалет?", "Дуже смачно!"] },
  lt: { tts: "lt-LT", zh: "立陶宛语", en: "Lithuanian", p: ["Laba diena", "Ačiū", "Kiek kainuoja?", "Kur tualetas?", "Labai skanu!"] },
  lv: { tts: "lv-LV", zh: "拉脱维亚语", en: "Latvian", p: ["Labdien", "Paldies", "Cik maksā?", "Kur ir tualete?", "Ļoti garšīgi!"] },
  et: { tts: "et-EE", zh: "爱沙尼亚语", en: "Estonian", p: ["Tere", "Aitäh", "Kui palju maksab?", "Kus on tualett?", "Väga maitsev!"] },
  fi: { tts: "fi-FI", zh: "芬兰语", en: "Finnish", p: ["Hei", "Kiitos", "Paljonko maksaa?", "Missä on vessa?", "Herkullista!"] },
  sv: { tts: "sv-SE", zh: "瑞典语", en: "Swedish", p: ["Hej", "Tack", "Vad kostar det?", "Var är toaletten?", "Jättegott!"] },
  no: { tts: "nb-NO", zh: "挪威语", en: "Norwegian", p: ["Hei", "Takk", "Hvor mye koster det?", "Hvor er toalettet?", "Kjempegodt!"] },
  da: { tts: "da-DK", zh: "丹麦语", en: "Danish", p: ["Hej", "Tak", "Hvad koster det?", "Hvor er toilettet?", "Lækkert!"] },
  is: { tts: "is-IS", zh: "冰岛语", en: "Icelandic", p: ["Halló", "Takk", "Hvað kostar þetta?", "Hvar er klósettið?", "Namm!"] },
  mt: { tts: "mt-MT", zh: "马耳他语", en: "Maltese", p: ["Bonġu", "Grazzi", "Kemm jiswa?", "Fejn hi t-tojlet?", "Tajjeb ħafna!"] },
  ht: { tts: "fr-FR", zh: "海地克里奥尔语", en: "Haitian Creole", p: ["Bonjou", "Mèsi", "Konbyen sa koute?", "Kote twalèt la?", "Li bon anpil!"] },
  sm: { tts: "sm-WS", zh: "萨摩亚语", en: "Samoan", p: ["Talofa", "Fa'afetai", "E fia le tau?", "O fea le faleuila?", "Manaia!"] },
  to: { tts: "to-TO", zh: "汤加语", en: "Tongan", p: ["Mālō e lelei", "Mālō", "'Oku fiha?", "Ko fē 'a e falemālōlō?", "Ifo 'aupito!"] },
  fj: { tts: "fj-FJ", zh: "斐济语", en: "Fijian", p: ["Bula", "Vinaka", "E vica?", "Evei na valelailai?", "Totoka sara!"] }
};

const LANG_BY_COUNTRY = {};
function _cl(lang, codes) { for (const a2 of codes.split(" ")) LANG_BY_COUNTRY[a2] = lang; }
_cl("en", "US GB CA AU NZ IE SG NG GH SL GM LR ZM ZW MW UG BW NA SZ LS ZA SS ER FJ PG SB VU KI TV NR FM MH PW CK NU GU MP AS BZ GY JM TT BB BS GD LC VC DM KN AG AI MS TC VG VI KY BM FK GI SH IM JE GG");
_cl("es", "ES MX GT SV HN NI CR PA CU DO CO VE EC PE BO PY UY CL AR GQ PR");
_cl("fr", "FR BE LU MC CD CG GA CM CI SN ML BF NE TD BJ TG GN DJ KM MG BI RW HT NC PF WF GP MQ RE YT PM GF CF");
_cl("ar", "SA AE QA BH KW OM YE JO IQ SY LB PS EG LY TN DZ SD MR EH MA");
_cl("pt", "PT BR AO MZ CV GW ST TL");
_cl("ru", "RU BY");
_cl("de", "DE AT CH LI");
_cl("it", "IT SM VA");
_cl("nl", "NL SR AW CW SX BQ");
_cl("el", "GR CY");
_cl("tr", "TR");
_cl("zh", "CN TW HK MO");
_cl("ja", "JP"); _cl("ko", "KR KP");
_cl("vi", "VN"); _cl("th", "TH"); _cl("id", "ID"); _cl("ms", "MY BN"); _cl("tl", "PH");
_cl("my", "MM"); _cl("lo", "LA"); _cl("km", "KH");
_cl("hi", "IN"); _cl("ur", "PK"); _cl("bn", "BD"); _cl("ne", "NP"); _cl("si", "LK"); _cl("dv", "MV"); _cl("dz", "BT");
_cl("fa", "IR AF"); _cl("he", "IL");
_cl("mn", "MN"); _cl("kk", "KZ"); _cl("ky", "KG"); _cl("uz", "UZ"); _cl("tg", "TJ"); _cl("tk", "TM");
_cl("az", "AZ"); _cl("ka", "GE"); _cl("hy", "AM");
_cl("sw", "KE TZ");
_cl("am", "ET"); _cl("so", "SO");
_cl("pl", "PL"); _cl("cs", "CZ"); _cl("sk", "SK"); _cl("hu", "HU"); _cl("ro", "RO MD");
_cl("bg", "BG"); _cl("sr", "RS ME"); _cl("hr", "HR"); _cl("bs", "BA"); _cl("sl", "SI"); _cl("mk", "MK"); _cl("sq", "AL XK");
_cl("uk", "UA"); _cl("lt", "LT"); _cl("lv", "LV"); _cl("et", "EE");
_cl("fi", "FI"); _cl("sv", "SE AX"); _cl("no", "NO SJ"); _cl("da", "DK FO GL"); _cl("is", "IS");
_cl("mt", "MT");
_cl("sm", "WS"); _cl("to", "TO"); _cl("fj", "FJ");

// Cities / sights / foods for countries without a hand-written full guide.
// Each item: [English, 中文]
const EXTRA = {
  // ---- Europe ----
  AT: { c: [["Vienna", "维也纳"], ["Salzburg", "萨尔茨堡"], ["Innsbruck", "因斯布鲁克"]], s: [["Schönbrunn Palace", "美泉宫"], ["Hallstatt", "哈尔施塔特"], ["Hofburg", "霍夫堡宫"]], f: [["Wiener Schnitzel", "维也纳炸牛排"], ["Sachertorte", "萨赫蛋糕"], ["Apfelstrudel", "苹果卷"]] },
  BE: { c: [["Brussels", "布鲁塞尔"], ["Bruges", "布鲁日"], ["Antwerp", "安特卫普"]], s: [["Grand Place", "布鲁塞尔大广场"], ["Atomium", "原子球塔"], ["Bruges Canals", "布鲁日运河"]], f: [["Belgian Waffle", "比利时华夫饼"], ["Belgian Chocolate", "比利时巧克力"], ["Moules-frites", "青口薯条"]] },
  CZ: { c: [["Prague", "布拉格"], ["Český Krumlov", "克鲁姆洛夫"], ["Brno", "布尔诺"]], s: [["Charles Bridge", "查理大桥"], ["Prague Castle", "布拉格城堡"], ["Old Town Square", "老城广场"]], f: [["Goulash", "炖牛肉"], ["Trdelník", "烟囱卷"], ["Pilsner Beer", "皮尔森啤酒"]] },
  PL: { c: [["Warsaw", "华沙"], ["Kraków", "克拉科夫"], ["Gdańsk", "格但斯克"]], s: [["Wawel Castle", "瓦维尔城堡"], ["Auschwitz Memorial", "奥斯维辛纪念馆"], ["Old Town Kraków", "克拉科夫老城"]], f: [["Pierogi", "波兰饺子"], ["Żurek", "酸汤"], ["Bigos", "猎人炖菜"]] },
  HU: { c: [["Budapest", "布达佩斯"], ["Debrecen", "德布勒森"]], s: [["Parliament Building", "匈牙利国会大厦"], ["Fisherman's Bastion", "渔人堡"], ["Széchenyi Baths", "塞切尼温泉"]], f: [["Goulash Soup", "匈牙利牛肉汤"], ["Lángos", "兰戈斯炸饼"], ["Chimney Cake", "烟囱蛋糕"]] },
  RO: { c: [["Bucharest", "布加勒斯特"], ["Brașov", "布拉索夫"], ["Cluj-Napoca", "克卢日"]], s: [["Bran Castle", "布朗城堡（德古拉城堡）"], ["Transfăgărășan Road", "特兰法加拉山路"], ["Peleș Castle", "佩雷什城堡"]], f: [["Sarmale", "包菜卷"], ["Mămăligă", "玉米糊"], ["Mici", "烤肉卷"]] },
  BG: { c: [["Sofia", "索非亚"], ["Plovdiv", "普罗夫迪夫"], ["Varna", "瓦尔纳"]], s: [["Rila Monastery", "里拉修道院"], ["Alexander Nevsky Cathedral", "亚历山大·涅夫斯基大教堂"], ["Sunny Beach", "阳光海滩"]], f: [["Banitsa", "奶酪酥饼"], ["Shopska Salad", "牧羊人沙拉"], ["Kebapche", "烤肉条"]] },
  HR: { c: [["Zagreb", "萨格勒布"], ["Dubrovnik", "杜布罗夫尼克"], ["Split", "斯普利特"]], s: [["Dubrovnik Old Town", "杜布罗夫尼克老城"], ["Plitvice Lakes", "十六湖国家公园"], ["Diocletian's Palace", "戴克里先宫"]], f: [["Peka", "铁钟焖肉"], ["Black Risotto", "墨鱼炖饭"], ["Ćevapi", "烤肉肠"]] },
  RS: { c: [["Belgrade", "贝尔格莱德"], ["Novi Sad", "诺维萨德"]], s: [["Kalemegdan Fortress", "卡莱梅格丹城堡"], ["St. Sava Temple", "圣萨瓦教堂"]], f: [["Ćevapi", "烤肉肠"], ["Pljeskavica", "塞尔维亚肉饼"]] },
  SI: { c: [["Ljubljana", "卢布尔雅那"], ["Bled", "布莱德"]], s: [["Lake Bled", "布莱德湖"], ["Postojna Cave", "波斯托伊纳溶洞"]], f: [["Potica", "核桃卷"], ["Kranjska Sausage", "克拉尼香肠"]] },
  SK: { c: [["Bratislava", "布拉迪斯拉发"], ["Košice", "科希策"]], s: [["Bratislava Castle", "布拉迪斯拉发城堡"], ["High Tatras", "高塔特拉山"]], f: [["Bryndzové Halušky", "羊奶酪土豆团"], ["Kapustnica", "酸菜汤"]] },
  BA: { c: [["Sarajevo", "萨拉热窝"], ["Mostar", "莫斯塔尔"]], s: [["Stari Most", "莫斯塔尔古桥"], ["Baščaršija", "老巴扎"]], f: [["Ćevapi", "烤肉肠"], ["Burek", "肉馅酥饼"]] },
  MK: { c: [["Skopje", "斯科普里"], ["Ohrid", "奥赫里德"]], s: [["Lake Ohrid", "奥赫里德湖"], ["Matka Canyon", "马特卡峡谷"]], f: [["Tavče Gravče", "焗豆"], ["Ajvar", "红椒酱"]] },
  AL: { c: [["Tirana", "地拉那"], ["Berat", "培拉特"], ["Sarandë", "萨兰达"]], s: [["Berat Old Town", "培拉特千窗之城"], ["Albanian Riviera", "阿尔巴尼亚里维埃拉"], ["Butrint", "布特林特遗址"]], f: [["Byrek", "酥皮饼"], ["Tavë Kosi", "酸奶焗羊肉"]] },
  ME: { c: [["Podgorica", "波德戈里察"], ["Kotor", "科托尔"], ["Budva", "布德瓦"]], s: [["Bay of Kotor", "科托尔湾"], ["Sveti Stefan", "圣斯特凡岛"], ["Durmitor", "杜米托尔国家公园"]], f: [["Njeguši Prosciutto", "涅古什火腿"], ["Kacamak", "玉米土豆糊"]] },
  XK: { c: [["Pristina", "普里什蒂纳"], ["Prizren", "普里兹伦"]], s: [["Prizren Old Town", "普里兹伦老城"], ["Rugova Canyon", "鲁戈瓦峡谷"]], f: [["Flija", "千层饼"], ["Burek", "肉馅酥饼"]] },
  NO: { c: [["Oslo", "奥斯陆"], ["Bergen", "卑尔根"], ["Tromsø", "特罗姆瑟"]], s: [["Geirangerfjord", "盖朗厄尔峡湾"], ["Lofoten Islands", "罗弗敦群岛"], ["Preikestolen", "布道石"]], f: [["Salmon", "三文鱼"], ["Brunost", "棕色奶酪"], ["Fårikål", "羊肉炖卷心菜"]] },
  SE: { c: [["Stockholm", "斯德哥尔摩"], ["Gothenburg", "哥德堡"], ["Kiruna", "基律纳"]], s: [["Gamla Stan", "斯德哥尔摩老城"], ["Vasa Museum", "瓦萨沉船博物馆"], ["Icehotel", "冰旅馆"]], f: [["Swedish Meatballs", "瑞典肉丸"], ["Cinnamon Bun", "肉桂卷"], ["Gravlax", "腌三文鱼"]] },
  FI: { c: [["Helsinki", "赫尔辛基"], ["Rovaniemi", "罗瓦涅米"], ["Turku", "图尔库"]], s: [["Santa Claus Village", "圣诞老人村"], ["Suomenlinna", "芬兰堡"], ["Lapland Auroras", "拉普兰极光"]], f: [["Salmon Soup", "三文鱼汤"], ["Karelian Pie", "卡累利阿派"], ["Cinnamon Roll", "肉桂卷"]] },
  DK: { c: [["Copenhagen", "哥本哈根"], ["Aarhus", "奥胡斯"], ["Odense", "欧登塞"]], s: [["Nyhavn", "新港彩色码头"], ["Little Mermaid", "小美人鱼像"], ["Tivoli Gardens", "趣伏里乐园"]], f: [["Smørrebrød", "开放式三明治"], ["Danish Pastry", "丹麦酥"], ["Hot Dog", "丹麦热狗"]] },
  IE: { c: [["Dublin", "都柏林"], ["Galway", "戈尔韦"], ["Cork", "科克"]], s: [["Cliffs of Moher", "莫赫悬崖"], ["Guinness Storehouse", "吉尼斯啤酒博物馆"], ["Ring of Kerry", "凯里之环"]], f: [["Irish Stew", "爱尔兰炖肉"], ["Guinness", "吉尼斯黑啤"], ["Soda Bread", "苏打面包"]] },
  EE: { c: [["Tallinn", "塔林"], ["Tartu", "塔尔图"]], s: [["Tallinn Old Town", "塔林老城"], ["Lahemaa National Park", "拉赫马国家公园"]], f: [["Black Bread", "黑面包"], ["Kama", "卡玛粉甜品"]] },
  LV: { c: [["Riga", "里加"], ["Jūrmala", "尤尔马拉"]], s: [["Riga Old Town", "里加老城"], ["Art Nouveau District", "新艺术建筑区"]], f: [["Grey Peas with Bacon", "培根灰豌豆"], ["Rye Bread", "黑麦面包"]] },
  LT: { c: [["Vilnius", "维尔纽斯"], ["Kaunas", "考纳斯"]], s: [["Vilnius Old Town", "维尔纽斯老城"], ["Trakai Castle", "特拉凯水上城堡"], ["Hill of Crosses", "十字架山"]], f: [["Cepelinai", "土豆肉团"], ["Cold Beet Soup", "冷甜菜汤"]] },
  UA: { c: [["Kyiv", "基辅"], ["Lviv", "利沃夫"], ["Odesa", "敖德萨"]], s: [["Kyiv Pechersk Lavra", "基辅洞窟修道院"], ["Lviv Old Town", "利沃夫老城"], ["Sophia Cathedral", "圣索菲亚大教堂"]], f: [["Borscht", "红菜汤"], ["Varenyky", "乌克兰饺子"], ["Chicken Kyiv", "基辅炸鸡卷"]] },
  BY: { c: [["Minsk", "明斯克"], ["Brest", "布列斯特"]], s: [["Mir Castle", "米尔城堡"], ["Belovezhskaya Pushcha", "别洛韦日森林"]], f: [["Draniki", "土豆饼"], ["Machanka", "肉酱蘸饼"]] },
  MD: { c: [["Chișinău", "基希讷乌"], ["Orheiul Vechi", "旧奥尔海伊"]], s: [["Cricova Winery", "克里科瓦地下酒窖"], ["Orheiul Vechi Monastery", "旧奥尔海伊岩洞修道院"]], f: [["Mămăligă", "玉米糊"], ["Plăcinte", "摩尔多瓦馅饼"]] },
  AD: { c: [["Andorra la Vella", "安道尔城"]], s: [["Grandvalira Ski Area", "格兰瓦利拉滑雪场"], ["Caldea Spa", "卡尔迪亚温泉中心"]], f: [["Escudella", "安道尔炖菜"], ["Trinxat", "土豆卷心菜饼"]] },
  MC: { c: [["Monte Carlo", "蒙特卡洛"]], s: [["Monte Carlo Casino", "蒙特卡洛赌场"], ["Prince's Palace", "亲王宫"], ["F1 Circuit", "F1街道赛道"]], f: [["Barbagiuan", "菠菜炸饺"], ["Socca", "鹰嘴豆烤饼"]] },
  SM: { c: [["San Marino City", "圣马力诺城"]], s: [["Three Towers of San Marino", "圣马力诺三塔"], ["Mount Titano", "蒂塔诺山"]], f: [["Torta Tre Monti", "三峰塔蛋糕"], ["Piadina", "意式薄饼"]] },
  VA: { c: [["Vatican City", "梵蒂冈城"]], s: [["St. Peter's Basilica", "圣彼得大教堂"], ["Sistine Chapel", "西斯廷礼拜堂"], ["Vatican Museums", "梵蒂冈博物馆"]], f: [["Roman Cuisine nearby", "周边罗马美食"]] },
  LI: { c: [["Vaduz", "瓦杜兹"]], s: [["Vaduz Castle", "瓦杜兹城堡"], ["Alpine Trails", "阿尔卑斯步道"]], f: [["Käsknöpfle", "奶酪面疙瘩"]] },
  LU: { c: [["Luxembourg City", "卢森堡市"]], s: [["Bock Casemates", "博克炮台地道"], ["Old Quarter", "卢森堡老城"]], f: [["Judd mat Gaardebounen", "熏猪颈配蚕豆"], ["Gromperekichelcher", "土豆煎饼"]] },
  MT: { c: [["Valletta", "瓦莱塔"], ["Mdina", "姆迪纳"]], s: [["St. John's Co-Cathedral", "圣约翰副主教座堂"], ["Blue Lagoon Comino", "科米诺蓝潟湖"], ["Mdina Old City", "姆迪纳静城"]], f: [["Pastizzi", "酥皮豌豆饼"], ["Rabbit Stew", "炖兔肉"]] },
  CY: { c: [["Nicosia", "尼科西亚"], ["Limassol", "利马索尔"], ["Paphos", "帕福斯"]], s: [["Aphrodite's Rock", "爱神岩"], ["Kykkos Monastery", "基科斯修道院"], ["Nissi Beach", "尼西海滩"]], f: [["Halloumi", "哈罗米奶酪"], ["Souvla", "塞浦路斯烤肉"], ["Meze", "什锦小盘"]] },
  FO: { c: [["Tórshavn", "托尔斯港"]], s: [["Múlafossur Waterfall", "穆拉福瀑布"], ["Saksun Village", "萨克森村"]], f: [["Skerpikjøt", "风干羊肉"], ["Fresh Seafood", "海鲜"]] },
  GL: { c: [["Nuuk", "努克"], ["Ilulissat", "伊卢利萨特"]], s: [["Ilulissat Icefjord", "伊卢利萨特冰湾"], ["Northern Lights", "北极光"]], f: [["Suaasat", "格陵兰海豹汤"], ["Musk Ox", "麝牛肉"]] },
  GI: { c: [["Gibraltar", "直布罗陀"]], s: [["Rock of Gibraltar", "直布罗陀巨岩"], ["Barbary Macaques", "巴巴利猕猴"]], f: [["Calentita", "鹰嘴豆烤饼"], ["Fish and Chips", "炸鱼薯条"]] },
  IM: { c: [["Douglas", "道格拉斯"]], s: [["TT Race Course", "曼岛TT赛道"], ["Laxey Wheel", "拉克西大水车"]], f: [["Manx Kipper", "熏鲱鱼"], ["Queenies", "扇贝"]] },
  JE: { c: [["St Helier", "圣赫利尔"]], s: [["Mont Orgueil Castle", "奥格伊尔城堡"], ["Jersey War Tunnels", "泽西战争地道"]], f: [["Jersey Royals", "泽西新土豆"], ["Seafood Platter", "海鲜拼盘"]] },
  GG: { c: [["St Peter Port", "圣彼得港"]], s: [["Castle Cornet", "科尔内城堡"], ["Little Chapel", "小教堂"]], f: [["Guernsey Gâche", "根西果子面包"], ["Crab Sandwich", "蟹肉三明治"]] },
  AX: { c: [["Mariehamn", "玛丽港"]], s: [["Kastelholm Castle", "卡斯泰尔霍尔姆城堡"], ["Archipelago Cycling", "群岛骑行"]], f: [["Åland Pancake", "奥兰烤布丁饼"]] },
  SJ: { c: [["Longyearbyen", "朗伊尔城"]], s: [["Arctic Wilderness", "北极荒野"], ["Polar Bears Safari", "北极熊观赏"]], f: [["Reindeer Stew", "驯鹿炖肉"], ["Arctic Char", "北极红点鲑"]] },

  // ---- Asia ----
  KP: { c: [["Pyongyang", "平壤"], ["Kaesong", "开城"]], s: [["Juche Tower", "主体思想塔"], ["Kim Il-sung Square", "金日成广场"], ["DMZ Panmunjom", "板门店"]], f: [["Pyongyang Naengmyeon", "平壤冷面"], ["Kimchi", "泡菜"]] },
  TW: { c: [["Taipei", "台北"], ["Kaohsiung", "高雄"], ["Tainan", "台南"]], s: [["Taipei 101", "台北101"], ["Taroko Gorge", "太鲁阁峡谷"], ["Sun Moon Lake", "日月潭"]], f: [["Beef Noodle Soup", "牛肉面"], ["Bubble Tea", "珍珠奶茶"], ["Xiaolongbao", "小笼包"]] },
  HK: { c: [["Central", "中环"], ["Tsim Sha Tsui", "尖沙咀"]], s: [["Victoria Peak", "太平山顶"], ["Victoria Harbour", "维多利亚港"], ["Big Buddha", "天坛大佛"]], f: [["Dim Sum", "港式点心"], ["Roast Goose", "烧鹅"], ["Milk Tea", "港式奶茶"]] },
  MO: { c: [["Macau Peninsula", "澳门半岛"], ["Taipa", "氹仔"]], s: [["Ruins of St. Paul's", "大三巴牌坊"], ["Senado Square", "议事亭前地"], ["Cotai Strip", "路氹金光大道"]], f: [["Portuguese Egg Tart", "葡式蛋挞"], ["Pork Chop Bun", "猪扒包"], ["Almond Cookie", "杏仁饼"]] },
  MM: { c: [["Yangon", "仰光"], ["Mandalay", "曼德勒"], ["Bagan", "蒲甘"]], s: [["Shwedagon Pagoda", "仰光大金塔"], ["Bagan Temples", "蒲甘佛塔群"], ["Inle Lake", "茵莱湖"]], f: [["Mohinga", "鱼汤米线"], ["Tea Leaf Salad", "茶叶沙拉"], ["Shan Noodles", "掸邦面"]] },
  LA: { c: [["Vientiane", "万象"], ["Luang Prabang", "琅勃拉邦"], ["Vang Vieng", "万荣"]], s: [["Kuang Si Falls", "光西瀑布"], ["Pha That Luang", "塔銮"], ["Alms Giving Ceremony", "清晨布施"]], f: [["Larb", "老挝凉拌肉"], ["Sticky Rice", "糯米饭"], ["Or Lam", "老挝炖菜"]] },
  KH: { c: [["Phnom Penh", "金边"], ["Siem Reap", "暹粒"], ["Sihanoukville", "西哈努克市"]], s: [["Angkor Wat", "吴哥窟"], ["Bayon Temple", "巴戎寺"], ["Royal Palace", "金边王宫"]], f: [["Fish Amok", "阿莫克鱼"], ["Lok Lak", "洛乐牛肉"], ["Num Banh Chok", "高棉米线"]] },
  BN: { c: [["Bandar Seri Begawan", "斯里巴加湾市"]], s: [["Omar Ali Saifuddien Mosque", "赛福鼎清真寺"], ["Kampong Ayer", "水上村庄"]], f: [["Ambuyat", "西米糊"], ["Nasi Katok", "咖椰饭"]] },
  TL: { c: [["Dili", "帝力"]], s: [["Cristo Rei", "帝力基督像"], ["Atauro Island", "阿陶罗岛"]], f: [["Ikan Sabuko", "烤鱼"], ["Batar Daan", "玉米炖菜"]] },
  BD: { c: [["Dhaka", "达卡"], ["Chittagong", "吉大港"], ["Cox's Bazar", "科克斯巴扎尔"]], s: [["Sundarbans", "孙德尔本斯红树林"], ["Cox's Bazar Beach", "世界最长海滩"], ["Lalbagh Fort", "拉尔巴格堡"]], f: [["Hilsa Fish Curry", "鲥鱼咖喱"], ["Biryani", "达卡香饭"], ["Fuchka", "脆球小吃"]] },
  LK: { c: [["Colombo", "科伦坡"], ["Kandy", "康提"], ["Galle", "加勒"]], s: [["Sigiriya Rock", "狮子岩"], ["Temple of the Tooth", "佛牙寺"], ["Ella Nine Arch Bridge", "埃拉九拱桥"]], f: [["Rice and Curry", "斯里兰卡咖喱饭"], ["Hoppers", "碗形米饼"], ["Kottu Roti", "剁碎炒饼"]] },
  NP: { c: [["Kathmandu", "加德满都"], ["Pokhara", "博卡拉"]], s: [["Everest Base Camp", "珠峰大本营"], ["Boudhanath Stupa", "博达哈大佛塔"], ["Annapurna Circuit", "安纳普尔纳环线"]], f: [["Momo", "尼泊尔饺子"], ["Dal Bhat", "豆汤饭"], ["Newari Cuisine", "尼瓦尔风味"]] },
  BT: { c: [["Thimphu", "廷布"], ["Paro", "帕罗"]], s: [["Tiger's Nest Monastery", "虎穴寺"], ["Punakha Dzong", "普那卡宗"]], f: [["Ema Datshi", "辣椒奶酪"], ["Red Rice", "红米饭"]] },
  MV: { c: [["Malé", "马累"], ["Maafushi", "马富士岛"]], s: [["Overwater Villas", "水上屋"], ["Vaadhoo Glowing Beach", "瓦度岛荧光海"], ["Whale Shark Diving", "鲸鲨潜水"]], f: [["Mas Huni", "金枪鱼椰丝"], ["Garudhiya", "鱼汤"]] },
  PK: { c: [["Islamabad", "伊斯兰堡"], ["Lahore", "拉合尔"], ["Karachi", "卡拉奇"]], s: [["Badshahi Mosque", "巴德夏希清真寺"], ["Hunza Valley", "罕萨山谷"], ["Karakoram Highway", "喀喇昆仑公路"]], f: [["Biryani", "巴基斯坦香饭"], ["Nihari", "炖牛肉"], ["Chapli Kebab", "恰普利烤肉饼"]] },
  AF: { c: [["Kabul", "喀布尔"], ["Herat", "赫拉特"]], s: [["Band-e Amir Lakes", "班达米尔湖"], ["Herat Citadel", "赫拉特城堡"]], f: [["Kabuli Pulao", "阿富汗手抓饭"], ["Mantu", "阿富汗蒸饺"]] },
  IR: { c: [["Tehran", "德黑兰"], ["Isfahan", "伊斯法罕"], ["Shiraz", "设拉子"]], s: [["Naqsh-e Jahan Square", "伊玛目广场"], ["Persepolis", "波斯波利斯"], ["Nasir al-Mulk Mosque", "粉红清真寺"]], f: [["Kebab Koobideh", "波斯烤肉"], ["Ghormeh Sabzi", "香草炖肉"], ["Saffron Rice", "藏红花饭"]] },
  IQ: { c: [["Baghdad", "巴格达"], ["Erbil", "埃尔比勒"]], s: [["Erbil Citadel", "埃尔比勒城堡"], ["Babylon Ruins", "巴比伦遗址"]], f: [["Masgouf", "烤鲤鱼"], ["Dolma", "酿菜卷"]] },
  SY: { c: [["Damascus", "大马士革"], ["Aleppo", "阿勒颇"]], s: [["Umayyad Mosque", "倭马亚清真寺"], ["Krak des Chevaliers", "骑士堡"]], f: [["Shawarma", "沙威玛"], ["Fattoush", "黎凡特沙拉"]] },
  LB: { c: [["Beirut", "贝鲁特"], ["Byblos", "比布鲁斯"]], s: [["Jeita Grotto", "杰达溶洞"], ["Baalbek Temples", "巴勒贝克神庙"]], f: [["Hummus", "鹰嘴豆泥"], ["Tabbouleh", "塔布勒沙拉"], ["Manakish", "扎塔尔烤饼"]] },
  JO: { c: [["Amman", "安曼"], ["Aqaba", "亚喀巴"]], s: [["Petra", "佩特拉古城"], ["Wadi Rum", "瓦迪拉姆月亮谷"], ["Dead Sea", "死海"]], f: [["Mansaf", "羊肉酸奶饭"], ["Falafel", "炸豆丸"]] },
  IL: { c: [["Jerusalem", "耶路撒冷"], ["Tel Aviv", "特拉维夫"]], s: [["Western Wall", "西墙（哭墙）"], ["Old City Jerusalem", "耶路撒冷老城"], ["Masada", "马萨达"]], f: [["Hummus", "鹰嘴豆泥"], ["Shakshuka", "北非蛋"], ["Falafel", "炸豆丸"]] },
  PS: { c: [["Ramallah", "拉马拉"], ["Bethlehem", "伯利恒"]], s: [["Church of the Nativity", "圣诞教堂"], ["Old City Hebron", "希伯伦老城"]], f: [["Musakhan", "洋葱鸡肉饼"], ["Knafeh", "芝士甜糕"]] },
  SA: { c: [["Riyadh", "利雅得"], ["Jeddah", "吉达"], ["AlUla", "欧拉"]], s: [["Hegra (Mada'in Salih)", "石谷遗址"], ["Edge of the World", "世界边缘悬崖"], ["Jeddah Corniche", "吉达滨海路"]], f: [["Kabsa", "香料焖饭"], ["Arabic Coffee & Dates", "阿拉伯咖啡与椰枣"]] },
  QA: { c: [["Doha", "多哈"]], s: [["Museum of Islamic Art", "伊斯兰艺术博物馆"], ["Souq Waqif", "瓦其夫老市场"], ["The Pearl", "珍珠岛"]], f: [["Machboos", "卡塔尔焖饭"], ["Karak Tea", "卡拉克奶茶"]] },
  KW: { c: [["Kuwait City", "科威特城"]], s: [["Kuwait Towers", "科威特塔"], ["Grand Mosque", "大清真寺"]], f: [["Machboos", "焖饭"], ["Gers Ogaily", "藏红花蛋糕"]] },
  BH: { c: [["Manama", "麦纳麦"]], s: [["Bahrain Fort", "巴林堡"], ["Tree of Life", "生命之树"]], f: [["Machboos", "焖饭"], ["Halwa", "巴林甜糕"]] },
  OM: { c: [["Muscat", "马斯喀特"], ["Nizwa", "尼兹瓦"], ["Salalah", "塞拉莱"]], s: [["Sultan Qaboos Grand Mosque", "卡布斯大清真寺"], ["Wahiba Sands", "瓦希巴沙漠"], ["Wadi Shab", "沙布溪谷"]], f: [["Shuwa", "地坑烤羊"], ["Omani Halwa", "阿曼甜糕"]] },
  YE: { c: [["Sana'a", "萨那"], ["Aden", "亚丁"]], s: [["Old City of Sana'a", "萨那老城"], ["Socotra Island", "索科特拉岛"]], f: [["Saltah", "也门炖菜"], ["Mandi", "曼迪焖饭"]] },
  KZ: { c: [["Almaty", "阿拉木图"], ["Astana", "阿斯塔纳"]], s: [["Charyn Canyon", "恰伦峡谷"], ["Big Almaty Lake", "大阿拉木图湖"], ["Medeu Skating Rink", "麦迪奥冰场"]], f: [["Beshbarmak", "手抓面"], ["Baursak", "炸面团"], ["Kumis", "马奶酒"]] },
  UZ: { c: [["Tashkent", "塔什干"], ["Samarkand", "撒马尔罕"], ["Bukhara", "布哈拉"]], s: [["Registan Square", "列吉斯坦广场"], ["Bukhara Old City", "布哈拉老城"], ["Khiva Itchan Kala", "希瓦古城"]], f: [["Plov", "抓饭"], ["Samsa", "烤包子"], ["Lagman", "拉条子"]] },
  KG: { c: [["Bishkek", "比什凯克"], ["Karakol", "卡拉科尔"]], s: [["Issyk-Kul Lake", "伊塞克湖"], ["Ala Archa Gorge", "阿拉阿查峡谷"], ["Song-Kul Lake", "颂湖"]], f: [["Beshbarmak", "手抓面"], ["Kumis", "马奶酒"]] },
  TJ: { c: [["Dushanbe", "杜尚别"], ["Khujand", "苦盏"]], s: [["Pamir Highway", "帕米尔公路"], ["Iskanderkul Lake", "伊斯坎德尔湖"]], f: [["Qurutob", "馕泡酸奶"], ["Plov", "抓饭"]] },
  TM: { c: [["Ashgabat", "阿什哈巴德"], ["Mary", "马雷"]], s: [["Darvaza Gas Crater", "地狱之门"], ["Ancient Merv", "梅尔夫古城"]], f: [["Plov", "抓饭"], ["Manty", "蒸饺"]] },
  AZ: { c: [["Baku", "巴库"], ["Sheki", "舍基"]], s: [["Flame Towers", "火焰塔"], ["Old City Baku", "巴库老城"], ["Gobustan Mud Volcanoes", "戈布斯坦泥火山"]], f: [["Plov", "藏红花抓饭"], ["Dolma", "酿菜卷"], ["Qutab", "薄馅饼"]] },
  GE: { c: [["Tbilisi", "第比利斯"], ["Batumi", "巴统"], ["Kazbegi", "卡兹别吉"]], s: [["Old Tbilisi", "第比利斯老城"], ["Gergeti Trinity Church", "圣三一教堂"], ["Uplistsikhe Cave Town", "乌普利斯齐赫岩城"]], f: [["Khachapuri", "奶酪船饼"], ["Khinkali", "格鲁吉亚灌汤包"], ["Georgian Wine", "格鲁吉亚葡萄酒"]] },
  AM: { c: [["Yerevan", "埃里温"], ["Dilijan", "季利然"]], s: [["Geghard Monastery", "格加尔德修道院"], ["Lake Sevan", "塞凡湖"], ["Republic Square", "共和国广场"]], f: [["Khorovats", "亚美尼亚烤肉"], ["Lavash", "拉瓦什薄饼"]] },
  MN: { c: [["Ulaanbaatar", "乌兰巴托"], ["Kharkhorin", "哈拉和林"]], s: [["Gobi Desert", "戈壁沙漠"], ["Genghis Khan Statue", "成吉思汗骑马像"], ["Terelj National Park", "特勒吉国家公园"]], f: [["Khorkhog", "石头烤肉"], ["Buuz", "蒙古包子"], ["Airag", "马奶酒"]] },

  // ---- Africa ----
  TN: { c: [["Tunis", "突尼斯城"], ["Sousse", "苏塞"], ["Sidi Bou Said", "蓝白小镇"]], s: [["Carthage Ruins", "迦太基遗址"], ["Sidi Bou Said", "西迪布赛义德"], ["Sahara Douz", "杜兹沙漠"]], f: [["Couscous", "库斯库斯"], ["Brik", "突尼斯炸饺"], ["Harissa", "哈里萨辣酱"]] },
  DZ: { c: [["Algiers", "阿尔及尔"], ["Oran", "奥兰"]], s: [["Casbah of Algiers", "阿尔及尔卡斯巴"], ["Timgad Ruins", "提姆加德遗址"], ["Sahara Tassili", "塔西利岩画"]], f: [["Couscous", "库斯库斯"], ["Chakhchoukha", "碎饼炖肉"]] },
  LY: { c: [["Tripoli", "的黎波里"], ["Benghazi", "班加西"]], s: [["Leptis Magna", "大莱普提斯遗址"], ["Old Town Tripoli", "的黎波里老城"]], f: [["Couscous", "库斯库斯"], ["Bazin", "利比亚面团"]] },
  SD: { c: [["Khartoum", "喀土穆"], ["Port Sudan", "苏丹港"]], s: [["Meroë Pyramids", "麦罗埃金字塔"], ["Nile Confluence", "青白尼罗河交汇"]], f: [["Ful Medames", "炖蚕豆"], ["Kisra", "高粱薄饼"]] },
  SS: { c: [["Juba", "朱巴"]], s: [["Boma National Park", "博马国家公园"], ["White Nile", "白尼罗河"]], f: [["Kisra", "高粱薄饼"], ["Ful", "炖豆"]] },
  ET: { c: [["Addis Ababa", "亚的斯亚贝巴"], ["Lalibela", "拉利贝拉"], ["Gondar", "贡德尔"]], s: [["Lalibela Rock Churches", "拉利贝拉岩石教堂"], ["Simien Mountains", "西米恩山"], ["Danakil Depression", "达纳基尔洼地"]], f: [["Injera", "英吉拉酸饼"], ["Doro Wat", "辣炖鸡"], ["Ethiopian Coffee", "埃塞俄比亚咖啡"]] },
  ER: { c: [["Asmara", "阿斯马拉"], ["Massawa", "马萨瓦"]], s: [["Asmara Art Deco", "阿斯马拉装饰艺术建筑"], ["Dahlak Archipelago", "达赫拉克群岛"]], f: [["Injera", "英吉拉酸饼"], ["Zigni", "辣炖肉"]] },
  DJ: { c: [["Djibouti City", "吉布提市"]], s: [["Lake Assal", "阿萨勒盐湖"], ["Lake Abbe", "阿贝湖"]], f: [["Skoudehkaris", "吉布提焖饭"], ["Fah-fah", "辣炖汤"]] },
  SO: { c: [["Mogadishu", "摩加迪沙"], ["Hargeisa", "哈尔格萨"]], s: [["Laas Geel Caves", "拉斯吉尔岩画"], ["Lido Beach", "丽都海滩"]], f: [["Bariis Iskukaris", "索马里焖饭"], ["Camel Meat", "骆驼肉"]] },
  UG: { c: [["Kampala", "坎帕拉"], ["Entebbe", "恩德培"], ["Jinja", "金贾"]], s: [["Bwindi Gorilla Trekking", "布温迪大猩猩徒步"], ["Source of the Nile", "尼罗河源头"], ["Murchison Falls", "默奇森瀑布"]], f: [["Matoke", "蒸香蕉"], ["Rolex", "乌干达蛋卷饼"], ["Luwombo", "蕉叶蒸肉"]] },
  TZ: { c: [["Dar es Salaam", "达累斯萨拉姆"], ["Arusha", "阿鲁沙"], ["Zanzibar City", "桑给巴尔市"]], s: [["Serengeti", "塞伦盖蒂"], ["Mount Kilimanjaro", "乞力马扎罗山"], ["Zanzibar Stone Town", "桑给巴尔石头城"]], f: [["Nyama Choma", "烤肉"], ["Zanzibar Pizza", "桑给巴尔煎饼"], ["Ugali", "玉米糊"]] },
  RW: { c: [["Kigali", "基加利"], ["Musanze", "穆桑泽"]], s: [["Volcanoes Gorilla Trekking", "火山公园大猩猩徒步"], ["Lake Kivu", "基伍湖"], ["Genocide Memorial", "大屠杀纪念馆"]], f: [["Brochettes", "烤肉串"], ["Isombe", "木薯叶炖菜"]] },
  BI: { c: [["Bujumbura", "布琼布拉"], ["Gitega", "基特加"]], s: [["Lake Tanganyika", "坦噶尼喀湖"], ["Rusizi National Park", "鲁西齐国家公园"]], f: [["Mukeke Fish", "湖鱼"], ["Beans & Bananas", "豆焖香蕉"]] },
  MZ: { c: [["Maputo", "马普托"], ["Vilankulo", "维兰库洛"]], s: [["Bazaruto Archipelago", "巴扎鲁托群岛"], ["Tofo Beach", "托福海滩"]], f: [["Peri-Peri Prawns", "霹雳霹雳虾"], ["Matapa", "木薯叶花生糊"]] },
  ZM: { c: [["Lusaka", "卢萨卡"], ["Livingstone", "利文斯顿"]], s: [["Victoria Falls", "维多利亚瀑布"], ["South Luangwa", "南卢安瓜国家公园"]], f: [["Nshima", "玉米糊"], ["Kapenta", "小银鱼干"]] },
  ZW: { c: [["Harare", "哈拉雷"], ["Victoria Falls Town", "维多利亚瀑布镇"]], s: [["Victoria Falls", "维多利亚瀑布"], ["Great Zimbabwe Ruins", "大津巴布韦遗址"], ["Hwange National Park", "万基国家公园"]], f: [["Sadza", "玉米糊"], ["Nyama", "炖肉"]] },
  MW: { c: [["Lilongwe", "利隆圭"], ["Blantyre", "布兰太尔"]], s: [["Lake Malawi", "马拉维湖"], ["Mount Mulanje", "姆兰杰山"]], f: [["Chambo Fish", "湖鲷鱼"], ["Nsima", "玉米糊"]] },
  AO: { c: [["Luanda", "罗安达"], ["Lubango", "卢班戈"]], s: [["Kalandula Falls", "卡兰杜拉瀑布"], ["Tundavala Gap", "通达瓦拉裂谷"]], f: [["Moamba de Galinha", "棕榈油炖鸡"], ["Funge", "木薯糊"]] },
  NA: { c: [["Windhoek", "温得和克"], ["Swakopmund", "斯瓦科普蒙德"]], s: [["Sossusvlei Dunes", "苏丝斯黎红沙丘"], ["Etosha National Park", "埃托沙国家公园"], ["Deadvlei", "死亡谷"]], f: [["Game Meat", "野味烤肉"], ["Kapana", "街头烤肉"]] },
  BW: { c: [["Gaborone", "哈博罗内"], ["Maun", "马翁"]], s: [["Okavango Delta", "奥卡万戈三角洲"], ["Chobe National Park", "乔贝国家公园"]], f: [["Seswaa", "手撕炖牛肉"], ["Pap", "玉米糊"]] },
  NG: { c: [["Lagos", "拉各斯"], ["Abuja", "阿布贾"]], s: [["Lekki Conservation Centre", "莱基自然保护区"], ["Zuma Rock", "祖马岩"], ["Olumo Rock", "奥卢莫岩"]], f: [["Jollof Rice", "乔洛夫饭"], ["Suya", "苏亚烤肉"], ["Egusi Soup", "瓜子仁汤"]] },
  GH: { c: [["Accra", "阿克拉"], ["Kumasi", "库马西"], ["Cape Coast", "海岸角"]], s: [["Cape Coast Castle", "海岸角城堡"], ["Kakum Canopy Walk", "卡库姆树冠步道"], ["Labadi Beach", "拉巴迪海滩"]], f: [["Jollof Rice", "乔洛夫饭"], ["Banku & Tilapia", "班库配罗非鱼"], ["Waakye", "豆饭"]] },
  CI: { c: [["Abidjan", "阿比让"], ["Yamoussoukro", "亚穆苏克罗"]], s: [["Basilica of Our Lady of Peace", "和平之后大教堂"], ["Grand-Bassam", "大巴萨姆老城"]], f: [["Attiéké", "木薯粒饭"], ["Alloco", "炸香蕉"]] },
  SN: { c: [["Dakar", "达喀尔"], ["Saint-Louis", "圣路易"]], s: [["Gorée Island", "戈雷岛"], ["Lake Retba (Pink Lake)", "玫瑰湖"], ["African Renaissance Monument", "非洲复兴纪念碑"]], f: [["Thieboudienne", "塞内加尔鱼饭"], ["Yassa Chicken", "洋葱柠檬鸡"]] },
  ML: { c: [["Bamako", "巴马科"], ["Timbuktu", "廷巴克图"]], s: [["Great Mosque of Djenné", "杰内大清真寺"], ["Bandiagara Cliffs", "邦贾加拉悬崖"]], f: [["Tigadèguèna", "花生酱炖肉"], ["Jollof", "西非焖饭"]] },
  BF: { c: [["Ouagadougou", "瓦加杜古"], ["Bobo-Dioulasso", "博博迪乌拉索"]], s: [["Sindou Peaks", "辛杜石峰"], ["Grand Mosque Bobo", "博博大清真寺"]], f: [["Riz Gras", "油饭"], ["Tô", "小米糊"]] },
  NE: { c: [["Niamey", "尼亚美"], ["Agadez", "阿加德兹"]], s: [["Agadez Grand Mosque", "阿加德兹大清真寺"], ["Ténéré Desert", "泰内雷沙漠"]], f: [["Djerma Rice", "杰尔马饭"], ["Kilishi", "肉干"]] },
  TD: { c: [["N'Djamena", "恩贾梅纳"]], s: [["Zakouma National Park", "扎库马国家公园"], ["Ennedi Plateau", "恩内迪高原"]], f: [["Boule", "小米团"], ["Grilled Fish", "烤鱼"]] },
  BJ: { c: [["Cotonou", "科托努"], ["Ouidah", "维达"]], s: [["Ganvié Stilt Village", "冈维埃水上村"], ["Door of No Return", "不归门"]], f: [["Amiwo", "红玉米糊"], ["Grilled Chicken", "烤鸡"]] },
  TG: { c: [["Lomé", "洛美"], ["Kpalimé", "帕利梅"]], s: [["Koutammakou", "库塔马库泥塔屋"], ["Lomé Grand Market", "洛美大市场"]], f: [["Fufu", "富富"], ["Grilled Fish", "烤鱼"]] },
  GN: { c: [["Conakry", "科纳克里"]], s: [["Fouta Djallon Highlands", "富塔贾隆高原"], ["Îles de Los", "洛斯群岛"]], f: [["Poulet Yassa", "洋葱鸡"], ["Riz Gras", "油饭"]] },
  GW: { c: [["Bissau", "比绍"]], s: [["Bijagós Archipelago", "比热戈斯群岛"]], f: [["Jollof Rice", "西非焖饭"], ["Grilled Oysters", "烤生蚝"]] },
  SL: { c: [["Freetown", "弗里敦"]], s: [["River No. 2 Beach", "二号河海滩"], ["Tacugama Chimpanzee Sanctuary", "黑猩猩保护区"]], f: [["Cassava Leaves", "木薯叶炖菜"], ["Jollof Rice", "焖饭"]] },
  LR: { c: [["Monrovia", "蒙罗维亚"]], s: [["Sapo National Park", "萨波国家公园"], ["Providence Island", "普罗维登斯岛"]], f: [["Palm Butter", "棕榈奶油炖菜"], ["Fufu", "富富"]] },
  GM: { c: [["Banjul", "班珠尔"], ["Serekunda", "萨拉昆达"]], s: [["Kunta Kinteh Island", "昆塔金特岛"], ["Abuko Nature Reserve", "阿布科自然保护区"]], f: [["Domoda", "花生酱炖肉"], ["Benachin", "一锅饭"]] },
  MR: { c: [["Nouakchott", "努瓦克肖特"], ["Chinguetti", "欣盖提"]], s: [["Chinguetti Old Town", "欣盖提古城"], ["Banc d'Arguin", "阿尔金岩石礁国家公园"]], f: [["Thieboudienne", "鱼饭"], ["Camel Meat", "骆驼肉"]] },
  CM: { c: [["Yaoundé", "雅温得"], ["Douala", "杜阿拉"]], s: [["Mount Cameroon", "喀麦隆火山"], ["Kribi Beach", "克里比海滩"]], f: [["Ndolé", "苦叶炖菜"], ["Poulet DG", "总经理鸡"]] },
  GA: { c: [["Libreville", "利伯维尔"]], s: [["Loango National Park", "卢安果国家公园"], ["Pongara Beach", "蓬加拉海滩"]], f: [["Poulet Nyembwe", "棕榈果鸡"], ["Grilled Fish", "烤鱼"]] },
  GQ: { c: [["Malabo", "马拉博"], ["Bata", "巴塔"]], s: [["Pico Basile", "巴西莱峰"], ["Arena Blanca", "白沙滩"]], f: [["Succotash", "豆玉米炖"], ["Pepesup", "辣鱼汤"]] },
  CG: { c: [["Brazzaville", "布拉柴维尔"], ["Pointe-Noire", "黑角"]], s: [["Basilique Sainte-Anne", "圣安妮教堂"], ["Loufoulakari Falls", "卢富拉卡里瀑布"]], f: [["Poulet Moambé", "棕榈油炖鸡"], ["Saka Saka", "木薯叶"]] },
  CD: { c: [["Kinshasa", "金沙萨"], ["Goma", "戈马"]], s: [["Virunga National Park", "维龙加国家公园"], ["Nyiragongo Volcano", "尼拉贡戈火山"]], f: [["Moambe Chicken", "棕榈油炖鸡"], ["Fufu", "富富"]] },
  CF: { c: [["Bangui", "班吉"]], s: [["Boali Falls", "博阿利瀑布"], ["Dzanga-Sangha Reserve", "赞加-桑加保护区"]], f: [["Gozo", "木薯糊"], ["Grilled Meat", "烤肉"]] },
  ST: { c: [["São Tomé City", "圣多美市"]], s: [["Pico Cão Grande", "大狗峰"], ["Obo National Park", "奥博国家公园"]], f: [["Calulu", "熏鱼炖菜"], ["Chocolate", "本地可可巧克力"]] },
  CV: { c: [["Praia", "普拉亚"], ["Mindelo", "明德卢"]], s: [["Fogo Volcano", "福戈火山"], ["Santa Maria Beach", "圣玛丽亚海滩"]], f: [["Cachupa", "玉米豆炖菜"], ["Fresh Tuna", "金枪鱼"]] },
  KM: { c: [["Moroni", "莫罗尼"]], s: [["Mount Karthala", "卡尔塔拉火山"], ["Chomoni Beach", "乔莫尼海滩"]], f: [["Langouste à la Vanille", "香草龙虾"], ["Pilaou", "科摩罗焖饭"]] },
  MG: { c: [["Antananarivo", "塔那那利佛"], ["Morondava", "穆龙达瓦"]], s: [["Avenue of the Baobabs", "猴面包树大道"], ["Tsingy de Bemaraha", "贝马拉哈石林"], ["Lemur Parks", "狐猴保护区"]], f: [["Romazava", "牛肉叶菜汤"], ["Ravitoto", "木薯叶炖猪肉"]] },
  MU: { c: [["Port Louis", "路易港"], ["Grand Baie", "大湾"]], s: [["Le Morne Brabant", "莫纳山"], ["Seven Coloured Earths", "七色土"], ["Île aux Cerfs", "鹿岛"]], f: [["Dholl Puri", "豆蓉薄饼"], ["Octopus Curry", "章鱼咖喱"]] },
  SC: { c: [["Victoria", "维多利亚"], ["Beau Vallon", "博瓦隆"]], s: [["Anse Source d'Argent", "银泉滩"], ["Vallée de Mai", "五月谷"], ["Anse Lazio", "拉齐奥湾"]], f: [["Fish Curry", "克里奥尔鱼咖喱"], ["Grilled Job Fish", "烤鲷鱼"]] },
  LS: { c: [["Maseru", "马塞卢"]], s: [["Maletsunyane Falls", "马莱楚尼亚内瀑布"], ["Sani Pass", "萨尼山口"]], f: [["Papa & Moroho", "玉米糊配青菜"], ["Grilled Trout", "烤鳟鱼"]] },
  SZ: { c: [["Mbabane", "姆巴巴内"], ["Manzini", "曼齐尼"]], s: [["Mlilwane Wildlife Sanctuary", "姆利尔瓦内保护区"], ["Ezulwini Valley", "埃祖尔维尼谷"]], f: [["Sishwala", "玉米糊"], ["Braai Meat", "烤肉"]] },
  EH: { c: [["Laayoune", "阿尤恩"]], s: [["Saharan Dunes", "撒哈拉沙丘"]], f: [["Camel Tagine", "骆驼塔吉锅"], ["Mint Tea", "薄荷茶"]] },
  RE: { c: [["Saint-Denis", "圣但尼"]], s: [["Piton de la Fournaise", "富尔奈斯火山"], ["Cirque de Mafate", "马法特冰斗"]], f: [["Rougail Saucisse", "香肠红酱"], ["Cari", "留尼汪咖喱"]] },
  YT: { c: [["Mamoudzou", "马穆楚"]], s: [["Mayotte Lagoon", "马约特潟湖"]], f: [["Mataba", "木薯叶"], ["Grilled Fish", "烤鱼"]] },

  // ---- Americas ----
  GT: { c: [["Guatemala City", "危地马拉城"], ["Antigua", "安提瓜"]], s: [["Tikal Ruins", "蒂卡尔玛雅遗址"], ["Lake Atitlán", "阿蒂特兰湖"], ["Acatenango Volcano", "阿卡特南戈火山"]], f: [["Pepián", "佩皮安炖肉"], ["Tamales", "玉米粽"]] },
  BZ: { c: [["Belize City", "伯利兹城"], ["San Pedro", "圣佩德罗"]], s: [["Great Blue Hole", "大蓝洞"], ["Caye Caulker", "考克岛"], ["Xunantunich Ruins", "苏南图尼奇遗址"]], f: [["Rice and Beans", "椰香豆饭"], ["Fry Jacks", "炸面饼"]] },
  SV: { c: [["San Salvador", "圣萨尔瓦多"], ["Suchitoto", "苏奇托托"]], s: [["Santa Ana Volcano", "圣安娜火山"], ["Ruta de las Flores", "鲜花之路"]], f: [["Pupusa", "普普萨玉米饼"], ["Yuca Frita", "炸木薯"]] },
  HN: { c: [["Tegucigalpa", "特古西加尔巴"], ["Roatán", "罗阿坦岛"]], s: [["Copán Ruins", "科潘玛雅遗址"], ["Roatán Reefs", "罗阿坦潜水礁"]], f: [["Baleada", "豆泥卷饼"], ["Sopa de Caracol", "海螺汤"]] },
  NI: { c: [["Managua", "马那瓜"], ["Granada", "格拉纳达"], ["León", "莱昂"]], s: [["Ometepe Island", "奥梅特佩岛"], ["Masaya Volcano", "马萨亚火山"], ["Granada Colonial City", "格拉纳达殖民老城"]], f: [["Gallo Pinto", "红豆饭"], ["Vigorón", "酸菜猪皮木薯"]] },
  CR: { c: [["San José", "圣何塞"], ["La Fortuna", "拉福图纳"], ["Manuel Antonio", "曼努埃尔安东尼奥"]], s: [["Arenal Volcano", "阿雷纳尔火山"], ["Monteverde Cloud Forest", "蒙特维德云雾森林"], ["Manuel Antonio Park", "曼努埃尔安东尼奥公园"]], f: [["Gallo Pinto", "红豆饭"], ["Casado", "套餐饭"], ["Ceviche", "酸橘汁腌鱼"]] },
  PA: { c: [["Panama City", "巴拿马城"], ["Bocas del Toro", "博卡斯德尔托罗"]], s: [["Panama Canal", "巴拿马运河"], ["Casco Viejo", "老城区"], ["San Blas Islands", "圣布拉斯群岛"]], f: [["Sancocho", "鸡肉浓汤"], ["Patacones", "炸大蕉"]] },
  CU: { c: [["Havana", "哈瓦那"], ["Trinidad", "特立尼达"], ["Viñales", "维尼亚莱斯"]], s: [["Old Havana", "哈瓦那老城"], ["Varadero Beach", "巴拉德罗海滩"], ["Classic Cars & Malecón", "老爷车与海滨大道"]], f: [["Ropa Vieja", "手撕牛肉"], ["Mojito", "莫吉托"], ["Cuban Sandwich", "古巴三明治"]] },
  JM: { c: [["Kingston", "金斯敦"], ["Montego Bay", "蒙特哥贝"], ["Ocho Rios", "奥乔里奥斯"]], s: [["Dunn's River Falls", "邓恩河瀑布"], ["Seven Mile Beach", "七英里海滩"], ["Bob Marley Museum", "鲍勃·马利博物馆"]], f: [["Jerk Chicken", "牙买加烟熏烤鸡"], ["Ackee & Saltfish", "阿基果咸鱼"], ["Patties", "牙买加馅饼"]] },
  HT: { c: [["Port-au-Prince", "太子港"], ["Cap-Haïtien", "海地角"]], s: [["Citadelle Laferrière", "拉费里埃城堡"], ["Labadee", "拉巴地海滩"]], f: [["Griot", "炸猪肉"], ["Soup Joumou", "南瓜汤"]] },
  DO: { c: [["Santo Domingo", "圣多明各"], ["Punta Cana", "蓬塔卡纳"]], s: [["Zona Colonial", "殖民城区"], ["Bávaro Beach", "巴瓦罗海滩"], ["Saona Island", "绍纳岛"]], f: [["La Bandera", "国旗饭"], ["Mangú", "大蕉泥"], ["Sancocho", "杂烩浓汤"]] },
  PR: { c: [["San Juan", "圣胡安"], ["Ponce", "庞塞"]], s: [["Old San Juan", "老圣胡安"], ["El Yunque Rainforest", "云盖雨林"], ["Bioluminescent Bay", "荧光海湾"]], f: [["Mofongo", "蒜蓉大蕉泥"], ["Lechón", "烤乳猪"]] },
  BS: { c: [["Nassau", "拿骚"], ["Freeport", "自由港"]], s: [["Pig Beach", "猪岛"], ["Atlantis Paradise Island", "亚特兰蒂斯天堂岛"], ["Exuma Cays", "埃克苏马群岛"]], f: [["Conch Salad", "海螺沙拉"], ["Cracked Conch", "炸海螺"]] },
  BB: { c: [["Bridgetown", "布里奇敦"]], s: [["Harrison's Cave", "哈里森溶洞"], ["Carlisle Bay", "卡莱尔湾"]], f: [["Flying Fish & Cou-Cou", "飞鱼配库库"], ["Rum Punch", "朗姆潘趣"]] },
  TT: { c: [["Port of Spain", "西班牙港"]], s: [["Maracas Beach", "马拉卡斯海滩"], ["Caroni Bird Sanctuary", "卡罗尼鸟类保护区"]], f: [["Doubles", "双饼豆卷"], ["Bake & Shark", "鲨鱼堡"]] },
  GD: { c: [["St. George's", "圣乔治"]], s: [["Grand Anse Beach", "大安斯海滩"], ["Underwater Sculpture Park", "水下雕塑公园"]], f: [["Oil Down", "椰奶炖锅"], ["Nutmeg Treats", "肉豆蔻甜品"]] },
  LC: { c: [["Castries", "卡斯特里"], ["Soufrière", "苏弗里耶尔"]], s: [["The Pitons", "皮通山"], ["Sulphur Springs", "硫磺温泉"]], f: [["Green Fig & Saltfish", "青蕉咸鱼"], ["Creole Bread", "克里奥尔面包"]] },
  VC: { c: [["Kingstown", "金斯敦"], ["Bequia", "贝基亚岛"]], s: [["Tobago Cays", "多巴哥群礁"], ["La Soufrière Volcano", "苏弗里耶尔火山"]], f: [["Roasted Breadfruit & Jackfish", "烤面包果配鱼"]] },
  DM: { c: [["Roseau", "罗索"]], s: [["Boiling Lake", "沸腾湖"], ["Trafalgar Falls", "特拉法加瀑布"]], f: [["Mountain Chicken Legs", "山鸡腿"], ["Callaloo", "卡拉卢汤"]] },
  KN: { c: [["Basseterre", "巴斯特尔"]], s: [["Brimstone Hill Fortress", "硫磺山要塞"], ["Scenic Railway", "观光小火车"]], f: [["Stewed Saltfish", "炖咸鱼"], ["Sugar Cake", "椰糖糕"]] },
  AG: { c: [["St. John's", "圣约翰"]], s: [["Nelson's Dockyard", "纳尔逊船坞"], ["365 Beaches", "365海滩"]], f: [["Fungee & Pepperpot", "玉米团胡椒锅"], ["Black Pineapple", "黑菠萝"]] },
  AW: { c: [["Oranjestad", "奥拉涅斯塔德"]], s: [["Eagle Beach", "鹰滩"], ["Natural Pool", "天然泳池"]], f: [["Keshi Yena", "焗酿奶酪"], ["Fresh Seafood", "海鲜"]] },
  CW: { c: [["Willemstad", "威廉斯塔德"]], s: [["Handelskade Colorful Houses", "彩色房子码头"], ["Klein Curaçao", "小库拉索岛"]], f: [["Keshi Yena", "焗酿奶酪"], ["Stobá", "炖肉"]] },
  SX: { c: [["Philipsburg", "菲利普斯堡"]], s: [["Maho Beach (Plane Spotting)", "马霍海滩看飞机"], ["Great Bay", "大湾"]], f: [["Johnny Cakes", "约翰尼饼"], ["Conch & Dumplings", "海螺炖面团"]] },
  KY: { c: [["George Town", "乔治敦"]], s: [["Seven Mile Beach", "七英里海滩"], ["Stingray City", "魟鱼城"]], f: [["Turtle Stew", "海龟炖汤（传统）"], ["Conch Fritters", "海螺炸饼"]] },
  BM: { c: [["Hamilton", "汉密尔顿"]], s: [["Horseshoe Bay", "马蹄湾粉沙滩"], ["Crystal Caves", "水晶洞"]], f: [["Fish Chowder", "鱼杂烩汤"], ["Rum Swizzle", "朗姆调酒"]] },
  TC: { c: [["Cockburn Town", "科伯恩城"], ["Providenciales", "普罗维登西亚莱斯"]], s: [["Grace Bay Beach", "格雷斯湾"], ["Chalk Sound", "白垩湾"]], f: [["Conch Salad", "海螺沙拉"], ["Lobster", "龙虾"]] },
  VG: { c: [["Road Town", "罗德城"]], s: [["The Baths Virgin Gorda", "维尔京戈尔达浴场巨石"], ["Jost Van Dyke", "约斯特范代克岛"]], f: [["Anegada Lobster", "阿内加达龙虾"], ["Roti", "咖喱卷饼"]] },
  VI: { c: [["Charlotte Amalie", "夏洛特阿马利亚"]], s: [["Magens Bay", "马根斯湾"], ["Trunk Bay", "特朗克湾"]], f: [["Pate", "炸馅饼"], ["Fish & Fungi", "鱼配玉米团"]] },
  AI: { c: [["The Valley", "瓦利"]], s: [["Shoal Bay", "肖尔湾"], ["Sandy Ground", "桑迪格朗德"]], f: [["Grilled Crayfish", "烤小龙虾"], ["Johnny Cakes", "约翰尼饼"]] },
  MS: { c: [["Brades", "布莱兹"]], s: [["Soufrière Hills Volcano", "苏弗里耶尔火山"], ["Buried Plymouth", "被掩埋的普利茅斯"]], f: [["Goat Water", "山羊汤"]] },
  MQ: { c: [["Fort-de-France", "法兰西堡"]], s: [["Mount Pelée", "培雷火山"], ["Les Salines Beach", "盐场海滩"]], f: [["Accras", "炸鱼饼"], ["Colombo", "科伦坡咖喱"]] },
  GP: { c: [["Pointe-à-Pitre", "皮特尔角城"]], s: [["La Soufrière", "苏弗里耶尔火山"], ["Grande Anse Beach", "大安斯海滩"]], f: [["Bokit", "炸面包三明治"], ["Colombo", "科伦坡咖喱"]] },
  BL: { c: [["Gustavia", "古斯塔维亚"]], s: [["Shell Beach", "贝壳海滩"]], f: [["French-Creole Cuisine", "法式克里奥尔菜"]] },
  MF: { c: [["Marigot", "马里戈"]], s: [["Orient Bay", "东方湾"]], f: [["Creole Seafood", "克里奥尔海鲜"]] },
  BQ: { c: [["Kralendijk", "克拉伦代克"]], s: [["Bonaire Marine Park", "博奈尔海洋公园潜水"]], f: [["Fresh Catch", "海鲜"]] },
  TK: { c: [["Atafu", "阿塔富"]], s: [["Coral Atolls", "珊瑚环礁"]], f: [["Coconut Fish", "椰香鱼"]] },
  PN: { c: [["Adamstown", "亚当斯敦"]], s: [["Bounty Bay", "邦蒂湾"]], f: [["Local Honey", "皮特凯恩蜂蜜"]] },
  CO: { c: [["Bogotá", "波哥大"], ["Medellín", "麦德林"], ["Cartagena", "卡塔赫纳"]], s: [["Cartagena Old City", "卡塔赫纳老城"], ["Cocora Valley", "科科拉山谷"], ["Gold Museum", "黄金博物馆"]], f: [["Bandeja Paisa", "派萨拼盘"], ["Arepa", "玉米饼"], ["Ajiaco", "鸡肉土豆汤"]] },
  VE: { c: [["Caracas", "加拉加斯"], ["Mérida", "梅里达"]], s: [["Angel Falls", "天使瀑布"], ["Los Roques", "洛斯罗克斯群岛"]], f: [["Arepa", "玉米饼"], ["Pabellón Criollo", "国民套餐饭"]] },
  EC: { c: [["Quito", "基多"], ["Cuenca", "昆卡"], ["Guayaquil", "瓜亚基尔"]], s: [["Galápagos Islands", "加拉帕戈斯群岛"], ["Middle of the World", "赤道纪念碑"], ["Quilotoa Crater Lake", "基洛托阿火山湖"]], f: [["Ceviche", "酸橘汁腌鱼"], ["Llapingachos", "奶酪土豆饼"]] },
  BO: { c: [["La Paz", "拉巴斯"], ["Sucre", "苏克雷"], ["Uyuni", "乌尤尼"]], s: [["Salar de Uyuni", "乌尤尼盐湖（天空之镜）"], ["Lake Titicaca", "的的喀喀湖"], ["Death Road Cycling", "死亡公路骑行"]], f: [["Salteña", "玻利维亚馅饼"], ["Pique Macho", "杂烩肉盘"]] },
  PY: { c: [["Asunción", "亚松森"], ["Encarnación", "恩卡纳西翁"]], s: [["Jesuit Missions", "耶稣会传教区遗址"], ["Itaipu Dam", "伊泰普大坝"]], f: [["Sopa Paraguaya", "巴拉圭玉米糕"], ["Chipa", "奶酪面包圈"]] },
  UY: { c: [["Montevideo", "蒙得维的亚"], ["Punta del Este", "埃斯特角城"], ["Colonia", "科洛尼亚"]], s: [["La Mano (The Hand)", "海滩之手雕塑"], ["Colonia del Sacramento", "科洛尼亚老城"], ["Rambla", "海滨大道"]], f: [["Asado", "乌拉圭烤肉"], ["Chivito", "牛排三明治"], ["Mate", "马黛茶"]] },
  CL: { c: [["Santiago", "圣地亚哥"], ["Valparaíso", "瓦尔帕莱索"], ["San Pedro de Atacama", "圣佩德罗-德阿塔卡马"]], s: [["Atacama Desert", "阿塔卡马沙漠"], ["Torres del Paine", "百内国家公园"], ["Easter Island Moai", "复活节岛石像"]], f: [["Empanada de Pino", "智利馅饼"], ["Pastel de Choclo", "玉米派"], ["Chilean Wine", "智利葡萄酒"]] },
  GY: { c: [["Georgetown", "乔治敦"]], s: [["Kaieteur Falls", "凯厄图尔瀑布"], ["St. George's Cathedral", "圣乔治大教堂"]], f: [["Pepperpot", "胡椒炖肉"], ["Curry & Roti", "咖喱卷饼"]] },
  SR: { c: [["Paramaribo", "帕拉马里博"]], s: [["Historic Inner City", "帕拉马里博老城"], ["Brownsberg Nature Park", "布朗斯山自然公园"]], f: [["Pom", "波姆焗饭"], ["Roti", "咖喱卷饼"]] },
  GF: { c: [["Cayenne", "卡宴"], ["Kourou", "库鲁"]], s: [["Guiana Space Centre", "圭亚那航天中心"], ["Salvation Islands", "救赎群岛"]], f: [["Bouillon d'Awara", "阿瓦拉果炖汤"]] },
  FK: { c: [["Stanley", "斯坦利"]], s: [["Penguin Colonies", "企鹅栖息地"], ["Volunteer Point", "志愿者角"]], f: [["Fish and Chips", "炸鱼薯条"], ["Lamb", "羊肉"]] },
  PM: { c: [["Saint-Pierre", "圣皮埃尔"]], s: [["Île aux Marins", "水手岛"]], f: [["Tourtière", "肉派"], ["Seafood", "海鲜"]] },

  // ---- Oceania ----
  FJ: { c: [["Suva", "苏瓦"], ["Nadi", "楠迪"]], s: [["Mamanuca Islands", "玛玛努卡群岛"], ["Coral Coast", "珊瑚海岸"], ["Cloud 9 Floating Bar", "九霄云外浮吧"]], f: [["Kokoda", "椰汁腌鱼"], ["Lovo", "地炉大餐"]] },
  PG: { c: [["Port Moresby", "莫尔兹比港"], ["Mount Hagen", "芒特哈根"]], s: [["Kokoda Track", "科科达小径"], ["Tufi Fjords", "图菲峡湾"], ["Highlands Festivals", "高地部落节"]], f: [["Mumu", "地炉焖餐"], ["Sago", "西米"]] },
  SB: { c: [["Honiara", "霍尼亚拉"]], s: [["WWII Wrecks Diving", "二战沉船潜水"], ["Marovo Lagoon", "马罗沃潟湖"]], f: [["Poi", "芋泥"], ["Grilled Reef Fish", "烤礁鱼"]] },
  VU: { c: [["Port Vila", "维拉港"], ["Luganville", "卢甘维尔"]], s: [["Mount Yasur Volcano", "亚苏尔活火山"], ["Champagne Beach", "香槟海滩"], ["Blue Holes", "蓝洞"]], f: [["Lap Lap", "拉普拉普"], ["Coconut Crab", "椰子蟹"]] },
  WS: { c: [["Apia", "阿皮亚"]], s: [["To Sua Ocean Trench", "苏阿海沟天然泳池"], ["Lalomanu Beach", "拉洛马努海滩"]], f: [["Oka", "萨摩亚腌鱼"], ["Palusami", "椰浆芋叶"]] },
  TO: { c: [["Nuku'alofa", "努库阿洛法"]], s: [["Whale Swimming", "与鲸共游"], ["Mapu'a 'a Vaea Blowholes", "喷潮孔"]], f: [["Ota Ika", "椰汁生鱼"], ["Lu Pulu", "椰浆牛肉芋叶"]] },
  KI: { c: [["Tarawa", "塔拉瓦"]], s: [["WWII Relics", "二战遗迹"], ["Outer Atolls", "外环礁"]], f: [["Palusami", "椰浆芋叶"], ["Raw Fish", "生鱼"]] },
  TV: { c: [["Funafuti", "富纳富提"]], s: [["Funafuti Lagoon", "富纳富提潟湖"]], f: [["Pulaka", "沼泽芋"], ["Coconut Fish", "椰香鱼"]] },
  NR: { c: [["Yaren", "亚伦"]], s: [["Buada Lagoon", "布阿达潟湖"], ["Anibare Bay", "阿尼巴雷湾"]], f: [["Coconut Fish", "椰香鱼"], ["Black Noodles", "黑面"]] },
  FM: { c: [["Palikir", "帕利基尔"], ["Kolonia", "科洛尼亚"]], s: [["Nan Madol Ruins", "南马都尔水上遗址"], ["Chuuk Lagoon Wrecks", "楚克潟湖沉船"]], f: [["Breadfruit", "面包果"], ["Sashimi", "生鱼片"]] },
  MH: { c: [["Majuro", "马朱罗"]], s: [["Bikini Atoll", "比基尼环礁"], ["Arno Atoll", "阿尔诺环礁"]], f: [["Coconut Rice", "椰香饭"], ["Grilled Tuna", "烤金枪鱼"]] },
  PW: { c: [["Ngerulmud", "恩吉鲁穆德"], ["Koror", "科罗尔"]], s: [["Jellyfish Lake", "水母湖"], ["Rock Islands", "洛克群岛"], ["Blue Corner Diving", "蓝角潜水"]], f: [["Fruit Bat Soup", "果蝠汤（传统）"], ["Fresh Sashimi", "生鱼片"]] },
  CK: { c: [["Avarua", "阿瓦鲁阿"]], s: [["Aitutaki Lagoon", "艾图塔基潟湖"], ["Muri Beach", "穆里海滩"]], f: [["Ika Mata", "椰汁腌鱼"], ["Rukau", "芋叶菜"]] },
  NU: { c: [["Alofi", "阿洛菲"]], s: [["Limu Pools", "利穆天然泳池"], ["Whale Watching", "观鲸"]], f: [["Coconut Crab", "椰子蟹"], ["Takihi", "木瓜芋头烤盘"]] },
  NC: { c: [["Nouméa", "努美阿"]], s: [["Isle of Pines", "松树岛"], ["Heart of Voh", "沃心形红树林"]], f: [["Bougna", "地炉椰浆餐"], ["Fresh Seafood", "海鲜"]] },
  PF: { c: [["Papeete", "帕皮提"], ["Bora Bora", "波拉波拉"]], s: [["Bora Bora Lagoon", "波拉波拉潟湖"], ["Moorea", "茉莉雅岛"], ["Overwater Bungalows", "水上屋"]], f: [["Poisson Cru", "椰汁生鱼"], ["Po'e", "波利尼西亚果泥糕"]] },
  GU: { c: [["Hagåtña", "阿加尼亚"], ["Tumon", "杜梦湾"]], s: [["Tumon Bay", "杜梦湾"], ["Two Lovers Point", "恋人岬"]], f: [["Kelaguen", "查莫罗腌肉"], ["Red Rice", "红米饭"]] },
  MP: { c: [["Saipan", "塞班"]], s: [["Managaha Island", "军舰岛"], ["Grotto Diving", "蓝洞潜水"]], f: [["Kelaguen", "查莫罗腌肉"], ["Coconut Dishes", "椰香料理"]] },
  AS: { c: [["Pago Pago", "帕果帕果"]], s: [["National Park of American Samoa", "美属萨摩亚国家公园"]], f: [["Oka", "腌鱼"], ["Palusami", "椰浆芋叶"]] },
  WF: { c: [["Mata-Utu", "马塔乌图"]], s: [["Lake Lalolalo", "拉洛拉洛火山湖"]], f: [["Roast Pig", "烤猪"]] },
  NF: { c: [["Kingston", "金斯敦"]], s: [["Kingston Historic Area", "金斯敦历史区"]], f: [["Fresh Fish", "鲜鱼"]] },
  SH: { c: [["Jamestown", "詹姆斯敦"]], s: [["Jacob's Ladder", "雅各布天梯"], ["Napoleon's Tomb", "拿破仑之墓"]], f: [["Fishcakes", "鱼饼"], ["Plo", "圣赫勒拿炖饭"]] }
};

// Regional safety & taboo reference notes (used when a country has no hand-written notes)
const SUBNOTES = {
  "Northern Africa": { safety: { zh: "旅游区总体可控，防纠缠兜售与扒手；关注政局与边境地区安全提示；夏季高温防暑。", en: "Tourist areas are generally manageable; expect persistent vendors, guard against pickpockets, monitor political/border advisories, and beware summer heat." }, taboo: { zh: "多为穆斯林国家：着装保守，斋月白天勿当众饮食，用右手递物，拍摄当地人先征得同意。", en: "Mostly Muslim countries: dress modestly, don't eat publicly during Ramadan daytime, use the right hand, ask before photographing people." } },
  "Western Africa": { safety: { zh: "大城市注意夜间安全与财物保管，只用正规交通；出行前查看疟疾预防与疫苗要求（黄热病）。", en: "Use caution at night in big cities, guard valuables, use registered transport; check malaria precautions and yellow-fever vaccine requirements." }, taboo: { zh: "问候寒暄很重要，办事先打招呼；用右手递接物品；拍人先征得同意。", en: "Greetings matter — always say hello before business; use the right hand; ask before photographing people." } },
  "Middle Africa": { safety: { zh: "治安与政局需提前研判，部分地区不建议自由行；备好疟疾预防与黄热病疫苗证明。", en: "Research security and political conditions carefully — some areas are not for independent travel; carry yellow-fever certificates and malaria prophylaxis." }, taboo: { zh: "拍摄政府建筑、军警严格禁止；问候礼节重要；用右手递物。", en: "Never photograph government buildings or the military; greetings are important; use the right hand." } },
  "Eastern Africa": { safety: { zh: "Safari 全程听从向导；大城市防扒手与夜间出行风险；查看疟疾与黄热病要求。", en: "Follow your safari guide at all times; watch for pickpockets and avoid walking at night in big cities; check malaria and yellow-fever requirements." }, taboo: { zh: "拍摄当地人（尤其部落居民）需征得同意并可能需付费；沿海穆斯林地区着装保守。", en: "Ask (and often pay) before photographing people, especially tribal communities; dress modestly in Muslim coastal areas." } },
  "Southern Africa": { safety: { zh: "城市区域注意防抢：夜间乘车、财物勿外露；野生动物区域勿下车、勿投喂。", en: "Guard against robbery in cities — travel by car at night, keep valuables hidden; never leave vehicles or feed animals in wildlife areas." }, taboo: { zh: "种族历史话题敏感；进入部落村庄遵从当地礼仪。", en: "Racial history is a sensitive topic; follow local protocol when visiting villages." } },
  "North America": { safety: { zh: "总体安全但区域差异大；避开偏僻街区夜行，车内勿留贵重物品；紧急电话911。", en: "Generally safe with big neighborhood differences; avoid isolated areas at night, leave nothing visible in cars; emergency 911." }, taboo: { zh: "小费文化普遍（餐厅15-20%）；尊重个人空间与排队秩序。", en: "Tipping is expected (15–20% at restaurants); respect personal space and queues." } },
  "Central Europe": { safety: { zh: "治安良好；火车站与旅游热点防扒手；冬季山区注意路况。", en: "Very safe; watch for pickpockets at stations and hotspots; mind winter mountain roads." }, taboo: { zh: "守时是基本礼貌；周日多数商店关门；公共场合保持安静；不少地方偏好现金。", en: "Punctuality matters; most shops close on Sundays; keep voices down in public; some places prefer cash." } },
  "Caribbean": { safety: { zh: "旅游区总体安全；注意飓风季（6–11月）动态；贵重物品勿带上海滩，夜间乘车出行。", en: "Resort areas are generally safe; monitor hurricane season (Jun–Nov); don't take valuables to the beach, use taxis at night." }, taboo: { zh: "着装休闲但进教堂需得体；小费文化普遍（10–15%）；打招呼后再谈事是基本礼貌。", en: "Dress is casual but cover up in churches; tipping (10–15%) is common; greet people before getting to business." } },
  "Central America": { safety: { zh: "旅游线路总体可行；避免夜间长途巴士与偏僻街区；用正规出租车，现金分开放。", en: "Main tourist routes are fine; avoid night buses and rough neighborhoods; use registered taxis and split your cash." }, taboo: { zh: "教堂与玛雅圣地保持尊重；拍摄原住民先征得同意；讨价还价温和进行。", en: "Be respectful at churches and Maya sites; ask before photographing indigenous people; bargain gently." } },
  "South America": { safety: { zh: "大城市防手机抢夺与扒手：街头少露手机、夜间乘车；高海拔城市注意高原反应。", en: "Guard phones against snatching in big cities, use cars at night; mind altitude sickness in highland cities." }, taboo: { zh: "问候常行贴面礼；足球话题慎选立场；殖民历史与政治话题谨慎。", en: "Cheek-kiss greetings are common; pick football loyalties carefully; be tactful about politics and colonial history." } },
  "Central Asia": { safety: { zh: "治安总体良好；山区自驾与徒步注意路况天气；证件随身备查。", en: "Generally safe; take care with mountain roads and weather; carry ID for checks." }, taboo: { zh: "穆斯林传统地区着装保守；做客礼仪重（茶文化）；拍摄军警设施禁止。", en: "Dress modestly in traditional Muslim areas; guest/tea etiquette matters; never photograph military sites." } },
  "Eastern Asia": { safety: { zh: "治安普遍很好；注意交通规则差异与自然灾害预警。", en: "Very safe overall; mind traffic differences and natural-disaster alerts." }, taboo: { zh: "长辈优先、双手递物更礼貌；公共场合保持安静；排队秩序重要。", en: "Respect elders, hand items with both hands; keep quiet in public; queues matter." } },
  "South-Eastern Asia": { safety: { zh: "旅游区总体安全；防摩托飞车抢包与宰客骗局；雨季关注洪水与渡轮安全。", en: "Tourist areas are generally safe; watch for bag-snatching and scams; monitor floods and ferry safety in rainy season." }, taboo: { zh: "进寺庙脱鞋、遮肩膝；勿摸他人头部；对王室与宗教保持尊重；用右手递物。", en: "Remove shoes and cover up at temples; don't touch heads; respect royalty and religion; use the right hand." } },
  "Southern Asia": { safety: { zh: "注意饮食卫生（瓶装水）；女性避免夜间独行；人多场所防扒手；山区注意天气。", en: "Drink bottled water; women should avoid walking alone at night; guard against pickpockets in crowds; mind mountain weather." }, taboo: { zh: "左手视为不洁；进寺庙脱鞋；宗教场所着装保守；公共场合避免亲密行为。", en: "The left hand is unclean; remove shoes at temples; dress modestly at religious sites; avoid public displays of affection." } },
  "Western Asia": { safety: { zh: "海湾国家治安极好；其他地区出行前务必查看最新安全形势；夏季酷热防暑。", en: "Gulf states are extremely safe; check current advisories carefully for other areas; beware extreme summer heat." }, taboo: { zh: "着装保守、公共场合勿亲密；斋月白天勿当众饮食；拍摄当地人先征得同意；酒精管制严格。", en: "Dress modestly, no public affection; don't eat publicly in Ramadan daytime; ask before photographing locals; alcohol is restricted." } },
  "Eastern Europe": { safety: { zh: "治安总体良好；防车站扒手；出行前关注地区局势与航班政策。", en: "Generally safe; watch for pickpockets at stations; check regional situations and flight availability before travel." }, taboo: { zh: "进东正教堂着装得体（女性可备头巾）；送花要单数；干杯礼仪讲究。", en: "Dress properly in Orthodox churches (women may need a headscarf); give odd numbers of flowers; toasting has its rituals." } },
  "Northern Europe": { safety: { zh: "全球最安全地区之一；冬季注意冰雪路滑与极夜；户外活动告知行程。", en: "Among the safest regions on earth; mind icy roads and polar darkness in winter; log your plans for outdoor trips." }, taboo: { zh: "重视个人空间与安静；守时；桑拿礼仪入乡随俗；很多地方无现金。", en: "Respect personal space and quiet; be punctual; follow sauna etiquette; many places are cashless." } },
  "Western Europe": { safety: { zh: "总体安全；旅游热点严防扒手与手机抢夺；罢工可能影响交通。", en: "Generally safe; beware pickpockets and phone snatching at tourist hotspots; strikes may disrupt transport." }, taboo: { zh: "先问好再交谈是基本礼貌；餐厅保持音量；周日多数商店关门。", en: "Greet before you ask; keep voices down in restaurants; most shops close on Sundays." } },
  "Southern Europe": { safety: { zh: "总体安全；景点车站防扒手；夏季防晒防野火。", en: "Generally safe; watch for pickpockets at sights and stations; beware summer heat and wildfires." }, taboo: { zh: "教堂内遮肩膝；午休时间店铺可能关门；晚餐时间偏晚。", en: "Cover shoulders/knees in churches; shops may close for siesta; dinner starts late." } },
  "Southeast Europe": { safety: { zh: "总体安全友好；山区自驾注意路况；个别雷区遗留区域（波黑等）勿离开标记步道。", en: "Generally safe and welcoming; mind mountain roads; in a few areas (e.g., Bosnia) stay on marked trails due to legacy landmines." }, taboo: { zh: "巴尔干历史与民族话题非常敏感，避免评论；进修道院着装保守。", en: "Balkan history and ethnicity are highly sensitive topics — avoid taking sides; dress modestly at monasteries." } },
  "Australia and New Zealand": { safety: { zh: "非常安全；风险主要来自自然：防晒、离岸流、偏远地区自驾备足补给。", en: "Very safe; the risks are natural — extreme UV, rip currents, and remote drives need planning." }, taboo: { zh: "生物检疫极严，入境食品动植物必须申报；尊重原住民文化。", en: "Biosecurity is strict — declare all food and biological items; respect Indigenous cultures." } },
  "Melanesia": { safety: { zh: "度假区安全；部分城市（如莫尔兹比港）注意治安；关注气旋季。", en: "Resorts are safe; use caution in some cities (e.g., Port Moresby); monitor cyclone season." }, taboo: { zh: "村庄土地私有观念强，进村先征得同意；着装保守；周日多为礼拜日。", en: "Village land is private — ask before entering; dress modestly; Sundays are for church." } },
  "Micronesia": { safety: { zh: "治安很好；主要注意水上活动安全与台风季。", en: "Very safe; main risks are water activities and typhoon season." }, taboo: { zh: "岛屿社区保守，泳装只在海滩穿；尊重酋长制传统。", en: "Island communities are conservative — swimwear only at the beach; respect chief traditions." } },
  "Polynesia": { safety: { zh: "非常安全友好；注意离岸流与珊瑚割伤；气旋季11–4月。", en: "Very safe and friendly; mind rip currents and coral cuts; cyclone season Nov–Apr." }, taboo: { zh: "周日是安息日，商店多关门；进教堂着装得体；脱鞋入屋。", en: "Sunday is sacred — most shops close; dress up for church; remove shoes indoors." } },
  "Antarctic": { safety: { zh: "极端环境，仅限有组织考察/邮轮；严格听从探险队指挥。", en: "Extreme environment — organized expeditions only; follow expedition staff instructions strictly." }, taboo: { zh: "《南极条约》保护区：不得接近野生动物、不得带走任何物品。", en: "Antarctic Treaty rules: keep distance from wildlife, take nothing away." } }
};
